<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SavedByTheMaid.Domain\SavedByTheMaid.Domain.csproj" />
    <ProjectReference Include="..\SavedByTheMaid.Application\SavedByTheMaid.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Ensure resource files are included during Docker build context -->
    <EmbeddedResource Include="Resources.resx" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.0-rc" />
  </ItemGroup>

</Project>
