// <auto-generated />
using JempSoft.Core.Models.Invent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using netcore.Data;
using System;

namespace netcore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JempSoft.Core.Models.Administration.AvaliableMaid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvaliableCount");

                    b.Property<DateTime>("DayOfAvaliability");

                    b.Property<int>("ServiceCount");

                    b.HasKey("Id");

                    b.ToTable("AvaliableMaids");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Administration.AvaliableMaidHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Day");

                    b.Property<int>("EmployeeScheduleId");

                    b.Property<bool>("IsActive");

                    b.Property<TimeSpan>("Time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeScheduleId");

                    b.ToTable("AvaliableMaidHours");
                });

            modelBuilder.Entity("JempSoft.Core.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CleaningPlaceId");

                    b.Property<int>("CleaningPlaceRoomId");

                    b.Property<int>("ServiceTypeId");

                    b.HasKey("CartItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlace", b =>
                {
                    b.Property<int>("CleaningPlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CleaningPlaceRoomId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("CreatorUserId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<int>("DeleteUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("CleaningPlaceId");

                    b.HasIndex("CleaningPlaceRoomId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("CleaningPlaces");
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlaceCleaningPlaceRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CleaningPlaceId");

                    b.Property<int>("CleaningPlaceRoomId");

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.ToTable("CleaningPlaceCleaningPlaceRooms");
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlaceRoom", b =>
                {
                    b.Property<int>("CleaningPlaceRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("CreatorUserId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<int>("DeleteUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("CleaningPlaceRoomId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("CleaningPlaceRooms");
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlaceRoomServiceType", b =>
                {
                    b.Property<int>("CleaningPlaceRoomServiceTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CleaningPlaceRoomId");

                    b.Property<bool?>("IsActive");

                    b.Property<int>("ServiceTypeId");

                    b.HasKey("CleaningPlaceRoomServiceTypeId");

                    b.ToTable("CleaningPlaceRoomServiceTypes");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("ContactNumber")
                        .IsRequired();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Identification")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int?>("ServiceMeetId");

                    b.Property<int>("UserId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ServiceMeetId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("JempSoft.Core.Models.EmployeeMeetService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmployeeId");

                    b.Property<int>("ServiceMeetId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceMeetId");

                    b.ToTable("EmployeesMeetingServices");
                });

            modelBuilder.Entity("JempSoft.Core.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("EmployeeScheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AvaliableDay");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("IsActive");

                    b.HasKey("EmployeeScheduleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Branch", b =>
                {
                    b.Property<string>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<bool>("isDefaultBranch");

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.HasKey("branchId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Customer", b =>
                {
                    b.Property<string>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<int>("size");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.HasKey("customerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.CustomerLine", b =>
                {
                    b.Property<string>("customerLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("gender");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasMaxLength(50);

                    b.Property<int>("salutation");

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("customerLineId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Product", b =>
                {
                    b.Property<string>("productId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("barcode")
                        .HasMaxLength(50);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("productType");

                    b.Property<string>("serialNumber")
                        .HasMaxLength(50);

                    b.Property<int>("uom");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.PurchaseOrder", b =>
                {
                    b.Property<string>("purchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("deliveryAddress")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("picVendor")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("poDate");

                    b.Property<string>("purchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("purchaseOrderStatus");

                    b.Property<string>("purchaseReceiveNumber");

                    b.Property<string>("referenceNumberExternal")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasMaxLength(30);

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("purchaseOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("vendorId");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.Property<string>("purchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<decimal>("discountAmount");

                    b.Property<decimal>("price");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<string>("purchaseOrderId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<decimal>("totalAmount");

                    b.HasKey("purchaseOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("PurchaseOrderLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Receiving", b =>
                {
                    b.Property<string>("receivingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("purchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("receivingDate");

                    b.Property<string>("receivingNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("vendorDO")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("vendorInvoice")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("receivingId");

                    b.HasIndex("branchId");

                    b.HasIndex("purchaseOrderId");

                    b.HasIndex("vendorId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Receiving");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.ReceivingLine", b =>
                {
                    b.Property<string>("receivingLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyReceive");

                    b.Property<string>("receivingId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("receivingLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("receivingId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ReceivingLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.SalesOrder", b =>
                {
                    b.Property<string>("salesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("deliveryAddress")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("picCustomer")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberExternal")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasMaxLength(30);

                    b.Property<string>("salesOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("salesOrderStatus");

                    b.Property<string>("salesShipmentNumber");

                    b.Property<DateTime>("soDate");

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.HasKey("salesOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.SalesOrderLine", b =>
                {
                    b.Property<string>("salesOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<decimal>("discountAmount");

                    b.Property<decimal>("price");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<string>("salesOrderId")
                        .HasMaxLength(38);

                    b.Property<decimal>("totalAmount");

                    b.HasKey("salesOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("salesOrderId");

                    b.ToTable("SalesOrderLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Shipment", b =>
                {
                    b.Property<string>("shipmentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("customerPO")
                        .HasMaxLength(50);

                    b.Property<int>("expeditionMode");

                    b.Property<int>("expeditionType");

                    b.Property<string>("invoice")
                        .HasMaxLength(50);

                    b.Property<string>("salesOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("shipmentDate");

                    b.Property<string>("shipmentNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("shipmentId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("salesOrderId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.ShipmentLine", b =>
                {
                    b.Property<string>("shipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyShipment");

                    b.Property<string>("shipmentId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("shipmentLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("shipmentId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ShipmentLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferIn", b =>
                {
                    b.Property<string>("transferInId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("transferInDate");

                    b.Property<string>("transferInNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferInId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferIn");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferInLine", b =>
                {
                    b.Property<string>("transferInLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferInId")
                        .HasMaxLength(38);

                    b.HasKey("transferInLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferInId");

                    b.ToTable("TransferInLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOrder", b =>
                {
                    b.Property<string>("transferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("isIssued");

                    b.Property<bool>("isReceived");

                    b.Property<string>("picName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("transferOrderDate");

                    b.Property<string>("transferOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("transferOrderStatus");

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOrderId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOrder");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOrderLine", b =>
                {
                    b.Property<string>("transferOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<string>("transferOrderId")
                        .HasMaxLength(38);

                    b.HasKey("transferOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOrderId");

                    b.ToTable("TransferOrderLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOut", b =>
                {
                    b.Property<string>("transferOutId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("transferOutDate");

                    b.Property<string>("transferOutNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOutId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOut");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOutLine", b =>
                {
                    b.Property<string>("transferOutLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferOutId")
                        .HasMaxLength(38);

                    b.HasKey("transferOutLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOutId");

                    b.ToTable("TransferOutLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Vendor", b =>
                {
                    b.Property<string>("vendorId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<int>("size");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("vendorName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("vendorId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.VendorLine", b =>
                {
                    b.Property<string>("vendorLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("gender");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasMaxLength(50);

                    b.Property<int>("salutation");

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("vendorLineId");

                    b.HasIndex("vendorId");

                    b.ToTable("VendorLine");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Warehouse", b =>
                {
                    b.Property<string>("warehouseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("warehouseId");

                    b.HasIndex("branchId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceMeet", b =>
                {
                    b.Property<int>("ServiceMeetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("CartItemId");

                    b.Property<int>("Day");

                    b.Property<int>("Hour");

                    b.Property<int>("Minute");

                    b.Property<int>("Month");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.Property<bool>("isMorning");

                    b.HasKey("ServiceMeetId");

                    b.HasIndex("CartItemId");

                    b.ToTable("ServiceMeeting");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int>("CartItemId");

                    b.Property<int>("Day");

                    b.Property<int>("Hour");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsComplete");

                    b.Property<bool>("IsPayed");

                    b.Property<int>("Minute");

                    b.Property<int>("Month");

                    b.Property<int>("ServiceContactInfoId");

                    b.Property<decimal>("Tax");

                    b.Property<decimal>("TotalAmount");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("CartItemId");

                    b.HasIndex("ServiceContactInfoId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrderAdditionalService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdditionalServiceId");

                    b.Property<long>("ServiceOrderId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrderAdditionalServices");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrderContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalServiceInfo");

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceContactsInfo");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.AdditionalServiceType", b =>
                {
                    b.Property<int>("AdditionalServiceTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cost");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("CreatorUserId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<int>("DeleteUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<double>("Price");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("AdditionalServiceTypeId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("AdditionalServiceTypes");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.Calendar", b =>
                {
                    b.Property<int>("CalendarId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Day");

                    b.Property<bool>("IsHoliday");

                    b.Property<int>("Month");

                    b.Property<int>("Year");

                    b.HasKey("CalendarId");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdditionalServiceTypeId");

                    b.Property<string>("Address");

                    b.Property<int>("CartItemId");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Qty");

                    b.HasKey("OrderItemId");

                    b.HasIndex("AdditionalServiceTypeId");

                    b.HasIndex("CartItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CalendarId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CleaningPlaceRoomId");

                    b.Property<double>("Cost");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int>("CreatorUserId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<int>("DeleteUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<double>("Price");

                    b.Property<string>("Title");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("ServiceTypeId");

                    b.HasIndex("CleaningPlaceRoomId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("JempSoft.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("netcore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("ApplicationUserRole");

                    b.Property<bool>("BranchRole");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<bool>("CustomerLineRole");

                    b.Property<bool>("CustomerRole");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("HomeRole");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<bool>("ProductRole");

                    b.Property<bool>("PurchaseOrderLineRole");

                    b.Property<bool>("PurchaseOrderRole");

                    b.Property<bool>("ReceivingLineRole");

                    b.Property<bool>("ReceivingRole");

                    b.Property<bool>("SalesOrderLineRole");

                    b.Property<bool>("SalesOrderRole");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("ShipmentLineRole");

                    b.Property<bool>("ShipmentRole");

                    b.Property<bool>("StockRole");

                    b.Property<bool>("TransferInLineRole");

                    b.Property<bool>("TransferInRole");

                    b.Property<bool>("TransferOrderLineRole");

                    b.Property<bool>("TransferOrderRole");

                    b.Property<bool>("TransferOutLineRole");

                    b.Property<bool>("TransferOutRole");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<bool>("VendorLineRole");

                    b.Property<bool>("VendorRole");

                    b.Property<bool>("WarehouseRole");

                    b.Property<bool>("isSuperAdmin");

                    b.Property<string>("profilePictureUrl");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Administration.AvaliableMaidHour", b =>
                {
                    b.HasOne("JempSoft.Core.Models.EmployeeSchedule", "EmployeeSchedule")
                        .WithMany()
                        .HasForeignKey("EmployeeScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlace", b =>
                {
                    b.HasOne("JempSoft.Core.Models.CleaningPlaceRoom")
                        .WithMany("CleaningPlaces")
                        .HasForeignKey("CleaningPlaceRoomId");

                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.CleaningPlaceRoom", b =>
                {
                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Employee", b =>
                {
                    b.HasOne("JempSoft.Core.Models.ServiceMeet")
                        .WithMany("Maids")
                        .HasForeignKey("ServiceMeetId");

                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.EmployeeMeetService", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.ServiceMeet", "MeetService")
                        .WithMany()
                        .HasForeignKey("ServiceMeetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.CustomerLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Customer", "customer")
                        .WithMany("customerLine")
                        .HasForeignKey("customerId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.PurchaseOrder", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderLine")
                        .HasForeignKey("purchaseOrderId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Receiving", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("JempSoft.Core.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany()
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.ReceivingLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.Receiving", "receiving")
                        .WithMany("receivingLine")
                        .HasForeignKey("receivingId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.SalesOrder", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.SalesOrderLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany("salesOrderLine")
                        .HasForeignKey("salesOrderId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Shipment", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.HasOne("JempSoft.Core.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany()
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.ShipmentLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.Shipment", "shipment")
                        .WithMany("shipmentLine")
                        .HasForeignKey("shipmentId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferIn", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferInLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.TransferIn", "transferIn")
                        .WithMany("transferInLine")
                        .HasForeignKey("transferInId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOrder", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOrderLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany("transferOrderLine")
                        .HasForeignKey("transferOrderId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOut", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("JempSoft.Core.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("JempSoft.Core.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.TransferOutLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("JempSoft.Core.Models.Invent.TransferOut", "transferOut")
                        .WithMany("transferOutLine")
                        .HasForeignKey("transferOutId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.VendorLine", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Vendor", "vendor")
                        .WithMany("vendorLine")
                        .HasForeignKey("vendorId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Invent.Warehouse", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceMeet", b =>
                {
                    b.HasOne("JempSoft.Core.Models.CartItem", "CartItem")
                        .WithMany()
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrder", b =>
                {
                    b.HasOne("JempSoft.Core.Models.CartItem", "CartItem")
                        .WithMany()
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.ServiceOrderContactInfo", "ServiceContactInfo")
                        .WithMany()
                        .HasForeignKey("ServiceContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrderAdditionalService", b =>
                {
                    b.HasOne("JempSoft.Core.Models.ServiceOrder", "ServiceOrder")
                        .WithMany("AdditionalServices")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceOrderContactInfo", b =>
                {
                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.AdditionalServiceType", b =>
                {
                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.OrderItem", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Services.AdditionalServiceType", "AdditionalServiceType")
                        .WithMany()
                        .HasForeignKey("AdditionalServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.CartItem", "CartItem")
                        .WithMany()
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.Services.Schedule", b =>
                {
                    b.HasOne("JempSoft.Core.Models.Services.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JempSoft.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JempSoft.Core.Models.ServiceType", b =>
                {
                    b.HasOne("JempSoft.Core.Models.CleaningPlaceRoom")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("CleaningPlaceRoomId");

                    b.HasOne("JempSoft.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("netcore.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
