<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-EService.Web-9F2AC463-7068-41E1-A023-74DD1C9C0370</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\cli\**" />
    <Content Remove="wwwroot\cli\**" />
    <EmbeddedResource Remove="wwwroot\cli\**" />
    <None Remove="wwwroot\cli\**" />
    <Compile Remove="Data\Migrations\**" />
    <Content Remove="Data\Migrations\**" />
    <EmbeddedResource Remove="Data\Migrations\**" />
    <None Remove="Data\Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JempSoft.Applications\JempSoft.Applications.csproj" />
    <ProjectReference Include="..\JempSoft.Core\JempSoft.Core.csproj" />
    <ProjectReference Include="..\JempSoft.Infraestructure\JempSoft.Infraestructure.csproj" />
  </ItemGroup>

</Project>
